version: "3"
services:
  database:
    container_name: daily_diet_db
    image: postgres:latest
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGPORT=5433
    ports:
      - "${DB_PORT}:5433"
    volumes:
      - daily_diet_db_data:/var/lib/postgresql/data

volumes:
  daily_diet_db_data:
    driver: local
  